title: "OCI GenAI RAG Stack with Bastion Service — v16"
schemaVersion: 1.1.0
variables:
  tenancy_ocid: { title: "Tenancy OCID", type: string, required: true }
  home_region: { title: "Home Region", type: string, required: true }
  region: { title: "Deployment Region", type: string, required: true }
  ssh_public_key: { title: "SSH Public Key", type: string, required: true }
  
  # Bastion Service Configuration
  enable_bastion_service:
    title: "Enable OCI Bastion Service"
    type: boolean
    default: true
    description: "Use managed OCI Bastion Service for secure access (recommended)"
  
  enable_bastion_sessions:
    title: "Create Default Bastion Sessions"
    type: boolean
    default: true
    description: "Create SSH and port forwarding sessions automatically"
  
  bastion_session_ttl:
    title: "Bastion Session TTL (hours)"
    type: number
    default: 3
    minimum: 1
    maximum: 3
    description: "Session timeout in hours (1-3 hours allowed)"
  
  # IP Access Control
  allowed_ssh_cidrs:
    title: "Allowed SSH IP Ranges (CIDR)"
    type: string
    default: "0.0.0.0/0"
    description: "Comma-separated CIDR blocks for SSH access (e.g., 203.0.113.5/32,198.51.100.0/24)"
  
  allowed_web_cidrs:
    title: "Allowed Web Access IP Ranges (CIDR)"
    type: string
    default: "0.0.0.0/0"
    description: "Comma-separated CIDR blocks for web access (Jupyter/Streamlit)"
  
  # Network Configuration
  enable_nat_gateway:
    title: "Enable NAT Gateway"
    type: boolean
    default: true
    description: "Enable NAT Gateway for private subnet internet access"
  
  # Authentication Options
  jupyter_enable_auth:
    title: "Enable Jupyter Authentication"
    type: boolean
    default: true
    description: "Enable password authentication for Jupyter Lab"
  
  jupyter_password:
    title: "Jupyter Lab Password"
    type: password
    required: false
    description: "Password for Jupyter Lab access (leave empty for token-based auth)"
  
  # Compartment Configuration
  create_compartment: { title: "Create Project Compartment", type: boolean, default: true }
  parent_compartment_ocid: { title: "Parent Compartment OCID", type: string }
  project_compartment_ocid: { title: "Existing Project Compartment OCID", type: string }
  compartment_name: { title: "Project Compartment Name", type: string, default: "genai-rag-project" }
  
  # Instance Configuration
  instance_shape: { title: "Instance Shape", type: string, default: "VM.Standard.E5.Flex" }
  instance_ocpus: { title: "OCPUs", type: number, default: 2 }
  instance_memory_gbs: { title: "Memory (GB)", type: number, default: 24 }
  boot_volume_size_gbs: { title: "Boot Volume Size (GB)", type: number, default: 100 }
  open_tcp_ports_csv: { title: "Open TCP Ports (CSV)", type: string, default: "22,8888,8501,1521" }
  create_policies: { title: "Create IAM Policies", type: boolean, default: true }

variableGroups:
  - title: "Basics"
    variables: [tenancy_ocid, home_region, region, ssh_public_key]
  - title: "Bastion Service & Security"
    variables: [enable_bastion_service, enable_bastion_sessions, bastion_session_ttl, allowed_ssh_cidrs, allowed_web_cidrs]
  - title: "Network Configuration"
    variables: [enable_nat_gateway]
  - title: "Authentication"
    variables: [jupyter_enable_auth, jupyter_password]
  - title: "Compartments"
    variables: [create_compartment, parent_compartment_ocid, project_compartment_ocid, compartment_name]
  - title: "Compute Instance"
    variables: [instance_shape, instance_ocpus, instance_memory_gbs, boot_volume_size_gbs, open_tcp_ports_csv]
  - title: "IAM"
    variables: [create_policies]
